// <auto-generated />
using System;
using Group5Flight.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group5Flights.Migrations
{
    [DbContext(typeof(AirBnBContext))]
    [Migration("20260426082727_Phase4Refactor")]
    partial class Phase4Refactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Group5Flight.Models.DomainModels.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "delta.png",
                            Name = "Delta Airlines"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "united.png",
                            Name = "United Airlines"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "american.png",
                            Name = "American Airlines"
                        });
                });

            modelBuilder.Entity("Group5Flight.Models.DomainModels.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Airbus 320 Family",
                            AirlineId = 1,
                            ArrivalTime = new DateTime(2026, 4, 27, 10, 30, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 27, 8, 0, 0, 0, DateTimeKind.Local),
                            Emission = "Low",
                            FlightCode = "DL1001",
                            From = "New York",
                            Price = 199.99m,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Boeing 737 Family",
                            AirlineId = 1,
                            ArrivalTime = new DateTime(2026, 4, 28, 13, 0, 0, 0, DateTimeKind.Local),
                            CabinType = "Business",
                            Date = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 28, 10, 0, 0, 0, DateTimeKind.Local),
                            Emission = "Medium",
                            FlightCode = "DL2002",
                            From = "Chicago",
                            Price = 499.99m,
                            To = "Los Angeles"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Airbus 320 Family",
                            AirlineId = 2,
                            ArrivalTime = new DateTime(2026, 4, 27, 12, 0, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 27, 9, 0, 0, 0, DateTimeKind.Local),
                            Emission = "Low",
                            FlightCode = "UA101",
                            From = "New York",
                            Price = 249.99m,
                            To = "Miami"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Boeing 737 Family",
                            AirlineId = 2,
                            ArrivalTime = new DateTime(2026, 4, 29, 9, 30, 0, 0, DateTimeKind.Local),
                            CabinType = "Basic Economy",
                            Date = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Local),
                            Emission = "High",
                            FlightCode = "UA202",
                            From = "Chicago",
                            Price = 149.99m,
                            To = "Dallas"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Airbus 320 Family",
                            AirlineId = 3,
                            ArrivalTime = new DateTime(2026, 4, 27, 16, 30, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 27, 14, 0, 0, 0, DateTimeKind.Local),
                            Emission = "Medium",
                            FlightCode = "AA303",
                            From = "Los Angeles",
                            Price = 179.99m,
                            To = "Seattle"
                        },
                        new
                        {
                            FlightId = 6,
                            AircraftType = "Boeing 737 Family",
                            AirlineId = 3,
                            ArrivalTime = new DateTime(2026, 4, 28, 9, 0, 0, 0, DateTimeKind.Local),
                            CabinType = "Business",
                            Date = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 28, 6, 0, 0, 0, DateTimeKind.Local),
                            Emission = "Low",
                            FlightCode = "AA404",
                            From = "New York",
                            Price = 399.99m,
                            To = "Miami"
                        },
                        new
                        {
                            FlightId = 7,
                            AircraftType = "Airbus 320 Family",
                            AirlineId = 1,
                            ArrivalTime = new DateTime(2026, 4, 29, 16, 0, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 29, 12, 0, 0, 0, DateTimeKind.Local),
                            Emission = "Medium",
                            FlightCode = "DL3003",
                            From = "Seattle",
                            Price = 299.99m,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightId = 8,
                            AircraftType = "Airbus 320 Family",
                            AirlineId = 2,
                            ArrivalTime = new DateTime(2026, 4, 27, 17, 30, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 27, 15, 0, 0, 0, DateTimeKind.Local),
                            Emission = "Low",
                            FlightCode = "UA505",
                            From = "Dallas",
                            Price = 229.99m,
                            To = "Los Angeles"
                        });
                });

            modelBuilder.Entity("Group5Flight.Models.DomainModels.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ReservationId");

                    b.HasIndex("FlightId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Group5Flight.Models.DomainModels.Flight", b =>
                {
                    b.HasOne("Group5Flight.Models.DomainModels.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group5Flight.Models.DomainModels.Reservation", b =>
                {
                    b.HasOne("Group5Flight.Models.DomainModels.Flight", "Flight")
                        .WithMany("Reservations")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Group5Flight.Models.DomainModels.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Group5Flight.Models.DomainModels.Flight", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
