name: Build and deploy ASP.Net Core app to Azure Web App - Group5Flights

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore Group5Flights.csproj

      - name: Build with dotnet
        run: dotnet build Group5Flights.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish Group5Flights.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B11568A3AFAC4FD1AB6779EA4D9D31D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1760E02E49264BBEB101F86AC71D2AF0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E0D76F7490064EDD91EEE344BD362365 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Group5Flights'
          slot-name: 'Production'
          package: .